package me.psikuvit.betterads.storage;

import com.amazonaws.HttpMethod;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.AmazonS3Exception;
import com.amazonaws.services.s3.model.GeneratePresignedUrlRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.S3Object;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.InputStreamResource;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.time.Duration;
import java.util.Date;
import java.util.Optional;

@Service
@Slf4j
public class StorageService {

    private final AmazonS3 s3;
    private final String bucket;

    public StorageService(@Value("${app.s3.bucket:}") String bucket,
                          @Value("${app.s3.region:us-east-1}") String region) {
        if (bucket == null || bucket.isBlank()) {
            throw new IllegalStateException(
                    "app.s3.bucket must be configured — refusing to start without a target bucket for uploads");
        }
        this.bucket = bucket;
        this.s3 = AmazonS3ClientBuilder.standard()
                .withRegion(region)
                .withCredentials(DefaultAWSCredentialsProviderChain.getInstance())
                .build();
    }

    public String presignGetUrl(String key, Duration duration) {
        log.debug("Presigning GET URL for key={}, expiresIn={}", key, duration);
        Date expiration = new Date(System.currentTimeMillis() + duration.toMillis());
        GeneratePresignedUrlRequest req = new GeneratePresignedUrlRequest(bucket, key)
                .withMethod(HttpMethod.GET)
                .withExpiration(expiration);
        return s3.generatePresignedUrl(req).toString();
    }

    public String presignPutUrl(String key, String contentType, Duration duration) {
        log.debug("Presigning PUT URL for key={}, contentType={}, expiresIn={}", key, contentType, duration);
        Date expiration = new Date(System.currentTimeMillis() + duration.toMillis());
        GeneratePresignedUrlRequest req = new GeneratePresignedUrlRequest(bucket, key)
                .withMethod(HttpMethod.PUT)
                .withExpiration(expiration)
                .withContentType(contentType);
        // Binding contentType into the signed request means the client's PUT must send
        // a matching Content-Type header, or S3 will reject it with SignatureDoesNotMatch.
        return s3.generatePresignedUrl(req).toString();
    }

    public Optional<ObjectMetadata> getObjectMetadata(String key) {
        try {
            ObjectMetadata metadata = s3.getObjectMetadata(bucket, key);
            log.debug("Fetched metadata for key={}: size={}, contentType={}", key, metadata.getContentLength(), metadata.getContentType());
            return Optional.of(metadata);
        } catch (AmazonS3Exception e) {
            log.warn("Failed to fetch S3 metadata for key={}: {}", key, e.getMessage());
            return Optional.empty();
        }
    }

    // Streams rather than buffering into a byte[] - uploads can be up to
    // app.upload.max-size-bytes (200MB by default), too large to hold
    // wholesale in memory just to forward it to a moderation service.
    public InputStreamResource downloadObject(String key) {
        log.info("Downloading object from S3: key={}", key);
        S3Object obj = s3.getObject(bucket, key);
        return new InputStreamResource(obj.getObjectContent());
    }

    // Server-side upload for content generated by an AI provider (e.g. a
    // dubbed video downloaded from HuggingFace) rather than a client PUT.
    public void uploadObject(String key, byte[] content, String contentType) {
        log.info("Uploading object to S3: key={}, size={} bytes, contentType={}", key, content.length, contentType);
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(content.length);
        metadata.setContentType(contentType);
        s3.putObject(bucket, key, new ByteArrayInputStream(content), metadata);
        log.debug("Uploaded object to S3: key={}", key);
    }
}
